--[[--
Markdown formatter for myexport plugin.

Outputs a readable .md file with book title, author, chapters and
highlighted text, preserving optional notes.

@module koplugin.myexport.formatter.markdown
--]]--

local MarkdownFormatter = {}

-- Emoji for each highlight style (graceful fallback for plain readers)
local style_prefix = {
    lighten    = "> ",   -- blockquote looks good for lighten
    underscore = "> ",
    strikeout  = "> ",
    invert     = "> ",
}

local style_callout = {
    red = "> [!fail]",
    orange = "> [!warning]",
    yellow = "> [!question]",
    green = "> [!check]",
    olive = "> [!check]",
    cyan = "> [!tip]",
    blue = "> [!info]",
    purple = "> [!example]",
    gray = "> [!quote]",
}

local style_wrap = {
    lighten    = { "", "" },
    underscore = { "", "" },
    strikeout  = { "~~", "~~" },
    invert     = { "**", "**" },
}

local function wrap_style(text, drawer)
    local w = drawer and style_wrap[drawer]
    if w and w[1] ~= "" then
        return w[1] .. text .. w[2]
    end
    return text
end

--- Format all booknotes as Markdown.
-- @param clippings    table: { [title] = booknotes }
-- @param options      table: { incl_page=bool, incl_time=bool, incl_style=bool }
-- @return string
function MarkdownFormatter:format(clippings, options)
    options = options or {}
    local incl_page  = options.incl_page  ~= false   -- default true
    local incl_time  = options.incl_time  ~= false   -- default true
    local incl_style = options.incl_style ~= false   -- default true

    -- Sort by title
    local books = {}
    for _, book in pairs(clippings) do
        table.insert(books, book)
    end
    table.sort(books, function(a, b)
        return (a.title or "") < (b.title or "")
    end)

    local lines = {}

    for b_idx, book in ipairs(books) do
        --[[--
        -- Book header
        table.insert(lines, "# " .. (book.title or "Unknown"))
        
        if book.author and book.author ~= "" then
            table.insert(lines, "*" .. book.author .. "*")
        end
        
        table.insert(lines, "")
        --]]--

        table.insert(lines, "## QUOTES"")

        local prev_chapter = nil

        for _, chapter_group in ipairs(book) do
            for _, clipping in ipairs(chapter_group) do
                -- Chapter heading (only when it changes)
                local ch = clipping.chapter
                if ch and ch ~= prev_chapter then
                    table.insert(lines, "### " .. ch)
                    table.insert(lines, "")
                    prev_chapter = ch
                end

                -- Meta line (page and/or timestamp)
                local meta_parts = {}
                if incl_page and clipping.page then
                    table.insert(meta_parts, "pag. " .. tostring(clipping.page))
                end
                if incl_time and clipping.time then
                    table.insert(meta_parts,
                        os.date("%Y-%m-%d %H:%M", clipping.time))
                end
                if incl_style and clipping.drawer then
                    table.insert(meta_parts, clipping.drawer)
                end
                
                if #meta_parts > 0 then
                    local metas = table.concat(meta_parts, " · ")
                    --[[ old
                    table.insert(lines, "*" .. table.concat(meta_parts, " · ") .. "*")
                    table.insert(lines, "")
                    --]]
                end
                

                -- Highlight text
                if clipping.text and clipping.text ~= "" then
                    local prefix   = style_prefix[clipping.drawer] or "> "
                    local text     = wrap_style(clipping.text, clipping.drawer)
                    local callout  = style_callout[clipping.color] or "> [!quote]"
                    table.insert(lines, callout .. metas)
                    table.insert(lines, "> " .. text)
                    --[[--
                    -- Multi-line highlights: prefix every line
                    for ln in (text .. "\n"):gmatch("([^\n]*)\n") do
                        table.insert(lines, prefix .. ln)
                    end
                    --]]--
                    table.insert(lines, "")
                end

                -- Note
                if clipping.note and clipping.note ~= "" then
                    table.insert(lines, "📝 " .. clipping.note)
                    table.insert(lines, "")
                end

                table.insert(lines, "---")
                table.insert(lines, "")
            end
        end

        -- Separator between books
        if b_idx < #books then
            table.insert(lines, "")
            table.insert(lines, "---")
            table.insert(lines, "")
        end
    end

    -- Footer
    table.insert(lines, "")
    table.insert(lines,
        "*Generated by myexport · " .. os.date("%Y-%m-%d %H:%M:%S") .. "*")
    table.insert(lines, "")

    return table.concat(lines, "\n")
end

return MarkdownFormatter
