--[[--
Plain text formatter for myexport plugin.

Generates a clean, human-readable .txt file. No markup, no special characters
beyond basic ASCII separators.

@module koplugin.myexport.formatter.text
--]]--

local TextFormatter = {}

--- Format all booknotes as plain text.
-- @param clippings    table: { [title] = booknotes }
-- @param options      table: { incl_page=bool, incl_time=bool }
-- @return string
function TextFormatter:format(clippings, options)
    options = options or {}
    local incl_page = options.incl_page ~= false   -- default true
    local incl_time = options.incl_time ~= false   -- default true

    -- Sort books by title
    local books = {}
    for _, book in pairs(clippings) do
        table.insert(books, book)
    end
    table.sort(books, function(a, b)
        return (a.title or "") < (b.title or "")
    end)

    local lines = {}
    local SEP_BOOK = string.rep("=", 60)
    local SEP_NOTE = string.rep("-", 40)

    for b_idx, book in ipairs(books) do
        -- Book header
        table.insert(lines, SEP_BOOK)
        table.insert(lines, (book.title or "Unknown"))
        if book.author and book.author ~= "" then
            table.insert(lines, "  " .. book.author)
        end
        table.insert(lines, SEP_BOOK)
        table.insert(lines, "")

        local prev_chapter = nil

        for _, chapter_group in ipairs(book) do
            for _, clipping in ipairs(chapter_group) do
                -- Chapter heading (only on change)
                local ch = clipping.chapter
                if ch and ch ~= prev_chapter then
                    table.insert(lines, "  [ " .. ch .. " ]")
                    table.insert(lines, "")
                    prev_chapter = ch
                end

                -- Meta info
                local meta_parts = {}
                if incl_page and clipping.page then
                    table.insert(meta_parts, "pag. " .. tostring(clipping.page))
                end
                if incl_time and clipping.time then
                    table.insert(meta_parts,
                        os.date("%Y-%m-%d %H:%M", clipping.time))
                end
                if #meta_parts > 0 then
                    table.insert(lines, "  [" .. table.concat(meta_parts, " | ") .. "]")
                end

                -- Highlight text (indented)
                if clipping.text and clipping.text ~= "" then
                    for ln in (clipping.text .. "\n"):gmatch("([^\n]*)\n") do
                        table.insert(lines, "  " .. ln)
                    end
                end

                -- Note
                if clipping.note and clipping.note ~= "" then
                    table.insert(lines, "  >> " .. clipping.note)
                end

                table.insert(lines, "  " .. SEP_NOTE)
                table.insert(lines, "")
            end
        end

        if b_idx < #books then
            table.insert(lines, "")
        end
    end

    -- Footer
    table.insert(lines, "")
    table.insert(lines,
        "Generated by myexport on " .. os.date("%Y-%m-%d %H:%M:%S"))
    table.insert(lines, "")

    return table.concat(lines, "\n")
end

return TextFormatter
